change exit codes

diff --git a/.github/actions/get_public_files/action.yml b/.github/actions/get_public_files/action.yml
--- a/.github/actions/get_public_files/action.yml
+++ b/.github/actions/get_public_files/action.yml
@@ -40,15 +40,15 @@ runs:
             } 
             file=functions_for_analyzing_git_db.sh
             echo "url=$url$file"
-#            wget -q -P /tmp $url$file
-#            {
-#              wget_result=$?
-#              if [ $wget_result -ne 0 ]; then
-#                echo "Failed to get files from strudel-public with $wget_result"
-#                exit 3
-#              fi
-#            }
-#            ls -alt /tmp/$file
+            wget -q -P /tmp $url$file
+            {
+              wget_result=$?
+              if [ $wget_result -ne 0 ]; then
+                echo "Failed to get files from strudel-public with $wget_result"
+                exit 3
+              fi
+            }
+            ls -alt /tmp/$file
 #
 #            # NOTE: MAIN BRANCH
 #            url="https://raw.githubusercontent.com/strudelbots/strudel-public/refs/heads/main/"
