test image tag settings

diff --git a/.github/actions/get_public_files/action.yml b/.github/actions/get_public_files/action.yml
--- a/.github/actions/get_public_files/action.yml
+++ b/.github/actions/get_public_files/action.yml
@@ -52,6 +52,7 @@ runs:
               fi
             } 
             ls -alt /tmp/release_to_image_map.json
+
             file=strudel_code/get_image_for_tag.py
             echo "url=$url$file"
             wget  -P /tmp $url$file
@@ -63,6 +64,18 @@ runs:
               fi
             } 
             ls -alt /tmp/get_image_for_tag.py
+
+            file=strudel_code/image_map_data_classes.py
+            echo "url=$url$file"
+            wget -q -P /tmp $url$file
+            {
+              wget_result=$?
+              if [ $wget_result -ne 0 ]; then
+                echo "Failed to get files from strudel-public with $wget_result"
+                exit 2
+              fi
+            } 
+            ls -alt /tmp/image_map_data_classes.py
 
 #      - name: get_public_files 2
 #        shell: bash
