test run 8

diff --git a/.github/actions/run_strudel/action.yml b/.github/actions/run_strudel/action.yml
--- a/.github/actions/run_strudel/action.yml
+++ b/.github/actions/run_strudel/action.yml
@@ -6,10 +6,6 @@ inputs:
     required: false
     default: 'none'
     type: string
-  last_commit:
-    description: 'The last commit message'
-    required: true
-    type: string
   changed_files:
     description: 'The changed files'
     required: true
@@ -24,7 +20,12 @@ runs:
            echo "files: ${{ inputs.changed_files }}"
            export ALL_CHANGED_FILES="${{ inputs.changed_files }}"
            echo "user_command: ${{ inputs.user_command }}"
-
+            if [[ ${{ inputs.user_command }} == 'none' ]]; then
+                echo "error: user command is none"
+                exit 1
+            else
+                echo "Start Running Strudel with user command: ${{ inputs.user_command }}"
+            fi
 #           echo " *** changed_files=$changed_files"
 #           export ALL_CHANGED_FILES=$changed_files
 #           echo " *** ALL_CHANGED_FILES=$ALL_CHANGED_FILES"
