trying sanity test

diff --git a/.github/workflows/run_strudel_test.yml b/.github/workflows/run_strudel_test.yml
--- a/.github/workflows/run_strudel_test.yml
+++ b/.github/workflows/run_strudel_test.yml
@@ -68,18 +68,20 @@ jobs:
             docker ps -a
             docker logs logs
 
-
-      - name: run strudel sanity test
-        run: |
-            echo "***   start sanity test"
-            export STATUSCODE=$(curl --silent --output /dev/null --write-out "%{http_code}" --location '127.0.0.1:8080/add_logs/' \
-            --header 'X-Request-Id: 7' \
-            --header 'Content-Type: application/json' \
-            --data '{"source": "test",
-            "file_content": "def foo():\n  print(a)",
-            "file_name": "test"}')
-            printf "\n***   status code is $STATUSCODE \n"
-            if [ $STATUSCODE -ne 200 ]; then echo "sanity test fails, status $STATUSCODE"; fi
-            if [ $STATUSCODE -ne 200 ]; then exit 22; fi
-            echo "***   end sanity test"
+      - name: sanity tests
+        uses: strudelbots/strudel-public/.github/actions/sanity-tests@5-map-action-to-specific-strudel-image
 #
+#      - name: run strudel sanity test
+#        run: |
+#            echo "***   start sanity test"
+#            export STATUSCODE=$(curl --silent --output /dev/null --write-out "%{http_code}" --location '127.0.0.1:8080/add_logs/' \
+#            --header 'X-Request-Id: 7' \
+#            --header 'Content-Type: application/json' \
+#            --data '{"source": "test",
+#            "file_content": "def foo():\n  print(a)",
+#            "file_name": "test"}')
+#            printf "\n***   status code is $STATUSCODE \n"
+#            if [ $STATUSCODE -ne 200 ]; then echo "sanity test fails, status $STATUSCODE"; fi
+#            if [ $STATUSCODE -ne 200 ]; then exit 22; fi
+#            echo "***   end sanity test"
+##
