run sanity test

diff --git a/.github/workflows/run_strudel_for_logs.yml b/.github/workflows/run_strudel_for_logs.yml
--- a/.github/workflows/run_strudel_for_logs.yml
+++ b/.github/workflows/run_strudel_for_logs.yml
@@ -30,8 +30,8 @@ jobs:
         with:
          python-version: '3.10.12'
 
-      - name: install poetry
-        run: echo "install poetry"
+#      - name: install poetry
+#        run: echo "install poetry"
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -59,3 +59,18 @@ jobs:
         run: |
             docker compose -f docker_compose_run.yml up -d
             sleep 10
+
+      - name: run strudel sanity test
+        run: |
+            echo "start sanity test"
+            export STATUSCODE=$(curl --silent --output /dev/stderr --write-out "%{http_code}" --location '127.0.0.1:8080/add_logs/' \
+            --header 'X-Request-Id: 7' \
+            --header 'Content-Type: application/json' \
+            --data '{"source": "test",
+            "file_content": "def foo():\n  print(a)",
+            "file_name": "test"}')
+            printf "\n\n****   status code is $STATUSCODE \n\n"
+            if [ $STATUSCODE -ne 200 ]; then echo "sanity test fails, status $STATUSCODE"; fi
+            if [ $STATUSCODE -ne 200 ]; then exit 22; fi
+            echo "**** end sanity test"
+            echo "**** end run strudel"
