reusable function to get files

diff --git a/.github/workflows/run_strudel_test.yml b/.github/workflows/run_strudel_test.yml
--- a/.github/workflows/run_strudel_test.yml
+++ b/.github/workflows/run_strudel_test.yml
@@ -43,22 +43,23 @@ jobs:
            echo "env ref=${{ env.ref }}"
 
       - name: get strudel-public files
-        shell: bash
-        env:
-          version_tag: ${{ env.ref }}
-        run: |
-            url="https://raw.githubusercontent.com/strudelbots/strudel-public/refs/heads/$version_tag/code/determine_strudel_action.sh"  
-            echo "url=$url"
-            wget -q -P /tmp $url
-            {
-              wget_result=$?
-              if [ $wget_result -ne 200 ]; then
-                echo "wget failed with $wget_result"
-                exit 1
-              fi
-            }
-              
-            ls -alt /tmp/determine_strudel_action.sh
+        uses: strudelbots/strudel-public/.github/actions/get-public-files@5-map-action-to-specific-strudel-image
+#        shell: bash
+#        env:
+#          version_tag: ${{ env.ref }}
+#        run: |
+#            url="https://raw.githubusercontent.com/strudelbots/strudel-public/refs/heads/$version_tag/code/determine_strudel_action.sh"
+#            echo "url=$url"
+#            wget -q -P /tmp $url
+#            {
+#              wget_result=$?
+#              if [ $wget_result -ne 0 ]; then
+#                echo "Failed to get files from strudel-public with $wget_result"
+#                exit 1
+#              fi
+#            }
+#
+#            ls -alt /tmp/determine_strudel_action.sh
 #      - name: Clone the Strudel manager Repository
 #        run: |
 #          export current_dir=$(pwd)
